# Generated by Django 4.2.5 on 2023-10-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, verbose_name='类别')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='TOKEN'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '收入'), (2, '支出')], verbose_name='分类')),
                ('ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='金额')),
                ('note', models.TextField(verbose_name='备注')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.category', verbose_name='类别')),
            ],
        ),
    ]
